### ISSUE TITLE
Job error

### ISSUE THREAD

**Issue by windsofchange** [promek/px-dns-da2cp#1]
Output from Jon No. 3

rsync: on remote machine: --usermap=*:named: unknown option
rsync error: syntax or usage error (code 1) at main.c(1422) [server=3.0.6]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]

**Comment by promek** [comment]
The rsync man page has the answer.

> For the --usermap option to have any effect, the -o (--owner) option must be used (or implied), and the receiver will need to be running as a super-user (see also the --fake-super option).


> For the --groupmap option to have any effect, the -g (--groups) option must be used (or implied), and the receiver will need to have permissions to set that group.
